baseURL = "https://jgonsior.de/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
disableKinds = ["taxonomy", "taxonomyTerm", "section", "sitemap", "tags", "categories"]
enableRobotsTXT = true
editor = "nvim"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Julius Gaenseri.ch"

[blackfriday]
extensions = ["hardLineBreak"]

[permalinks]
fixed = ":title/"
posts = "posts/:slug/"

[params]
author = "Julius Gonsior"
description = "Hello my friend!"
bio = "Hey! How nice of you to visit me here!"
secondLine = "If you feel like I can help you somehow"
thirdLine = "please reach out to me:"
avatar = "julius2.jpg"
favicon = "favicon.ico"
error404 = "Sorry, there is no such page."
# key = "https://keybase.io/jgonsior/sigs/LfZ5xSVadUUkVYLj9NxNEEX5iz1e1cLUDrBf"
#stylesheets = ["vncnt.css", "fontello.css"]

[params.contact]
email = "mailto:julius@gaenseri.ch"
github = "https://github.com/jgonsior"
linkedin = "https://linkedin.com/in/julius-gonsior-2790b3141/"
university = "https://wwwdb.inf.tu-dresden.de/our-group/team/julius-gonsior/"
# telegram = "https://telegram.me/jgonsior"


[taxonomies]
    category = "categories"
    tag = "tags"
